# Generated by Django 2.2.24 on 2021-12-13 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=100)),
                ('birthday', models.DateField(help_text='Enter date of your birthday')),
                ('gender', models.CharField(choices=[('men', 'men'), ('woman', 'woman')], help_text='Choose your gender type', max_length=100)),
                ('sex_orientation', models.CharField(choices=[('men', 'men'), ('woman', 'woman')], help_text='Choose your gender preference', max_length=100)),
                ('about', models.CharField(help_text='Enter short text about yourself', max_length=1000)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
